name: Greeter

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Your Name
      double:
        type: boolean
        description: Set to double the fun

jobs:
  greet:
    name: Greet
    uses: colindembovsky/reusable-workflows-env-secrets/.github/workflows/greeter.yml@main
    with:
      name: ${{ github.event.inputs.name }}
      double: ${{ fromJSON(github.event.inputs.double) }}
